/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrewAppRouteImport } from './routes/crew-app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalUsersRouteImport } from './routes/portal.users'
import { Route as PortalMobileRouteImport } from './routes/portal.mobile'
import { Route as PortalHospitalRouteImport } from './routes/portal.hospital'
import { Route as PortalFleetRouteImport } from './routes/portal.fleet'
import { Route as PortalEpcrRouteImport } from './routes/portal.epcr'
import { Route as PortalDispatchersRouteImport } from './routes/portal.dispatchers'
import { Route as PortalCrewRouteImport } from './routes/portal.crew'
import { Route as PortalCallsRouteImport } from './routes/portal.calls'
import { Route as PortalCadRouteImport } from './routes/portal.cad'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as PortalAnalyticsRouteImport } from './routes/portal.analytics'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as PortalHospitalIndexRouteImport } from './routes/portal.hospital.index'
import { Route as PortalDispatchersIndexRouteImport } from './routes/portal.dispatchers.index'
import { Route as PortalCrewIndexRouteImport } from './routes/portal.crew.index'
import { Route as PortalCadIndexRouteImport } from './routes/portal.cad.index'
import { Route as PortalBillingIndexRouteImport } from './routes/portal.billing.index'
import { Route as PortalAdminIndexRouteImport } from './routes/portal.admin.index'
import { Route as PortalHospitalReportsRouteImport } from './routes/portal.hospital.reports'
import { Route as PortalHospitalQueueRouteImport } from './routes/portal.hospital.queue'
import { Route as PortalHospitalIncomingRouteImport } from './routes/portal.hospital.incoming'
import { Route as PortalHospitalIftRouteImport } from './routes/portal.hospital.ift'
import { Route as PortalHospitalHandoverRouteImport } from './routes/portal.hospital.handover'
import { Route as PortalHospitalEpcrViewerRouteImport } from './routes/portal.hospital.epcr-viewer'
import { Route as PortalHospitalCommunicationRouteImport } from './routes/portal.hospital.communication'
import { Route as PortalDispatchersIdRouteImport } from './routes/portal.dispatchers.$id'
import { Route as PortalCrewRosterRouteImport } from './routes/portal.crew.roster'
import { Route as PortalCrewPerformanceRouteImport } from './routes/portal.crew.performance'
import { Route as PortalCrewLeaveRouteImport } from './routes/portal.crew.leave'
import { Route as PortalCrewDirectoryRouteImport } from './routes/portal.crew.directory'
import { Route as PortalCrewCommunicationsRouteImport } from './routes/portal.crew.communications'
import { Route as PortalCrewCertificationsRouteImport } from './routes/portal.crew.certifications'
import { Route as PortalCrewAttendanceRouteImport } from './routes/portal.crew.attendance'
import { Route as PortalCrewAssignmentsRouteImport } from './routes/portal.crew.assignments'
import { Route as PortalCrewIdRouteImport } from './routes/portal.crew.$id'
import { Route as PortalCadMessagesRouteImport } from './routes/portal.cad.messages'
import { Route as PortalCadHospitalRouteImport } from './routes/portal.cad.hospital'
import { Route as PortalCadFleetRouteImport } from './routes/portal.cad.fleet'
import { Route as PortalCadDispatchersRouteImport } from './routes/portal.cad.dispatchers'
import { Route as PortalCadCallsRouteImport } from './routes/portal.cad.calls'
import { Route as PortalBillingSettingsRouteImport } from './routes/portal.billing.settings'
import { Route as PortalBillingReportsRouteImport } from './routes/portal.billing.reports'
import { Route as PortalBillingPaymentsRouteImport } from './routes/portal.billing.payments'
import { Route as PortalBillingInvoicesRouteImport } from './routes/portal.billing.invoices'
import { Route as PortalBillingCustomersRouteImport } from './routes/portal.billing.customers'
import { Route as PortalBillingBillingRouteImport } from './routes/portal.billing.billing'
import { Route as PortalAdminWorkflowRouteImport } from './routes/portal.admin.workflow'
import { Route as PortalAdminUsersRouteImport } from './routes/portal.admin.users'
import { Route as PortalAdminSettingsRouteImport } from './routes/portal.admin.settings'
import { Route as PortalAdminRolesRouteImport } from './routes/portal.admin.roles'
import { Route as PortalAdminRoadmapRouteImport } from './routes/portal.admin.roadmap'
import { Route as PortalAdminReportsRouteImport } from './routes/portal.admin.reports'
import { Route as PortalAdminProfileRouteImport } from './routes/portal.admin.profile'
import { Route as PortalAdminOrganizationsRouteImport } from './routes/portal.admin.organizations'
import { Route as PortalAdminNotificationsRouteImport } from './routes/portal.admin.notifications'
import { Route as PortalAdminModulesRouteImport } from './routes/portal.admin.modules'
import { Route as PortalAdminMasterRouteImport } from './routes/portal.admin.master'
import { Route as PortalAdminIntegrationsRouteImport } from './routes/portal.admin.integrations'
import { Route as PortalAdminComplianceRouteImport } from './routes/portal.admin.compliance'
import { Route as PortalAdminAuditRouteImport } from './routes/portal.admin.audit'
import { Route as PortalCadCallsIndexRouteImport } from './routes/portal.cad.calls.index'
import { Route as PortalCadCallsActiveRouteImport } from './routes/portal.cad.calls.active'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewAppRoute = CrewAppRouteImport.update({
  id: '/crew-app',
  path: '/crew-app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUsersRoute = PortalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMobileRoute = PortalMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHospitalRoute = PortalHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFleetRoute = PortalFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEpcrRoute = PortalEpcrRouteImport.update({
  id: '/epcr',
  path: '/epcr',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDispatchersRoute = PortalDispatchersRouteImport.update({
  id: '/dispatchers',
  path: '/dispatchers',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCrewRoute = PortalCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCallsRoute = PortalCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCadRoute = PortalCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHospitalIndexRoute = PortalHospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalHospitalRoute,
} as any)
const PortalDispatchersIndexRoute = PortalDispatchersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalDispatchersRoute,
} as any)
const PortalCrewIndexRoute = PortalCrewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCadIndexRoute = PortalCadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCadRoute,
} as any)
const PortalBillingIndexRoute = PortalBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalAdminIndexRoute = PortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalHospitalReportsRoute = PortalHospitalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalHospitalRoute,
} as any)
const PortalHospitalQueueRoute = PortalHospitalQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => PortalHospitalRoute,
} as any)
const PortalHospitalIncomingRoute = PortalHospitalIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => PortalHospitalRoute,
} as any)
const PortalHospitalIftRoute = PortalHospitalIftRouteImport.update({
  id: '/ift',
  path: '/ift',
  getParentRoute: () => PortalHospitalRoute,
} as any)
const PortalHospitalHandoverRoute = PortalHospitalHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => PortalHospitalRoute,
} as any)
const PortalHospitalEpcrViewerRoute =
  PortalHospitalEpcrViewerRouteImport.update({
    id: '/epcr-viewer',
    path: '/epcr-viewer',
    getParentRoute: () => PortalHospitalRoute,
  } as any)
const PortalHospitalCommunicationRoute =
  PortalHospitalCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => PortalHospitalRoute,
  } as any)
const PortalDispatchersIdRoute = PortalDispatchersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalDispatchersRoute,
} as any)
const PortalCrewRosterRoute = PortalCrewRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCrewPerformanceRoute = PortalCrewPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCrewLeaveRoute = PortalCrewLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCrewDirectoryRoute = PortalCrewDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCrewCommunicationsRoute =
  PortalCrewCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => PortalCrewRoute,
  } as any)
const PortalCrewCertificationsRoute =
  PortalCrewCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => PortalCrewRoute,
  } as any)
const PortalCrewAttendanceRoute = PortalCrewAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCrewAssignmentsRoute = PortalCrewAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCrewIdRoute = PortalCrewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalCrewRoute,
} as any)
const PortalCadMessagesRoute = PortalCadMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalCadRoute,
} as any)
const PortalCadHospitalRoute = PortalCadHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => PortalCadRoute,
} as any)
const PortalCadFleetRoute = PortalCadFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => PortalCadRoute,
} as any)
const PortalCadDispatchersRoute = PortalCadDispatchersRouteImport.update({
  id: '/dispatchers',
  path: '/dispatchers',
  getParentRoute: () => PortalCadRoute,
} as any)
const PortalCadCallsRoute = PortalCadCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => PortalCadRoute,
} as any)
const PortalBillingSettingsRoute = PortalBillingSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalBillingReportsRoute = PortalBillingReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalBillingPaymentsRoute = PortalBillingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalBillingInvoicesRoute = PortalBillingInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalBillingCustomersRoute = PortalBillingCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalBillingBillingRoute = PortalBillingBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalBillingRoute,
} as any)
const PortalAdminWorkflowRoute = PortalAdminWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminUsersRoute = PortalAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminSettingsRoute = PortalAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminRolesRoute = PortalAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminRoadmapRoute = PortalAdminRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminReportsRoute = PortalAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminProfileRoute = PortalAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminOrganizationsRoute =
  PortalAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => PortalAdminRoute,
  } as any)
const PortalAdminNotificationsRoute =
  PortalAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PortalAdminRoute,
  } as any)
const PortalAdminModulesRoute = PortalAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminMasterRoute = PortalAdminMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminIntegrationsRoute = PortalAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminComplianceRoute = PortalAdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminAuditRoute = PortalAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalCadCallsIndexRoute = PortalCadCallsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCadCallsRoute,
} as any)
const PortalCadCallsActiveRoute = PortalCadCallsActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => PortalCadCallsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew-app': typeof CrewAppRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/billing': typeof PortalBillingRouteWithChildren
  '/portal/cad': typeof PortalCadRouteWithChildren
  '/portal/calls': typeof PortalCallsRoute
  '/portal/crew': typeof PortalCrewRouteWithChildren
  '/portal/dispatchers': typeof PortalDispatchersRouteWithChildren
  '/portal/epcr': typeof PortalEpcrRoute
  '/portal/fleet': typeof PortalFleetRoute
  '/portal/hospital': typeof PortalHospitalRouteWithChildren
  '/portal/mobile': typeof PortalMobileRoute
  '/portal/users': typeof PortalUsersRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/compliance': typeof PortalAdminComplianceRoute
  '/portal/admin/integrations': typeof PortalAdminIntegrationsRoute
  '/portal/admin/master': typeof PortalAdminMasterRoute
  '/portal/admin/modules': typeof PortalAdminModulesRoute
  '/portal/admin/notifications': typeof PortalAdminNotificationsRoute
  '/portal/admin/organizations': typeof PortalAdminOrganizationsRoute
  '/portal/admin/profile': typeof PortalAdminProfileRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/roadmap': typeof PortalAdminRoadmapRoute
  '/portal/admin/roles': typeof PortalAdminRolesRoute
  '/portal/admin/settings': typeof PortalAdminSettingsRoute
  '/portal/admin/users': typeof PortalAdminUsersRoute
  '/portal/admin/workflow': typeof PortalAdminWorkflowRoute
  '/portal/billing/billing': typeof PortalBillingBillingRoute
  '/portal/billing/customers': typeof PortalBillingCustomersRoute
  '/portal/billing/invoices': typeof PortalBillingInvoicesRoute
  '/portal/billing/payments': typeof PortalBillingPaymentsRoute
  '/portal/billing/reports': typeof PortalBillingReportsRoute
  '/portal/billing/settings': typeof PortalBillingSettingsRoute
  '/portal/cad/calls': typeof PortalCadCallsRouteWithChildren
  '/portal/cad/dispatchers': typeof PortalCadDispatchersRoute
  '/portal/cad/fleet': typeof PortalCadFleetRoute
  '/portal/cad/hospital': typeof PortalCadHospitalRoute
  '/portal/cad/messages': typeof PortalCadMessagesRoute
  '/portal/crew/$id': typeof PortalCrewIdRoute
  '/portal/crew/assignments': typeof PortalCrewAssignmentsRoute
  '/portal/crew/attendance': typeof PortalCrewAttendanceRoute
  '/portal/crew/certifications': typeof PortalCrewCertificationsRoute
  '/portal/crew/communications': typeof PortalCrewCommunicationsRoute
  '/portal/crew/directory': typeof PortalCrewDirectoryRoute
  '/portal/crew/leave': typeof PortalCrewLeaveRoute
  '/portal/crew/performance': typeof PortalCrewPerformanceRoute
  '/portal/crew/roster': typeof PortalCrewRosterRoute
  '/portal/dispatchers/$id': typeof PortalDispatchersIdRoute
  '/portal/hospital/communication': typeof PortalHospitalCommunicationRoute
  '/portal/hospital/epcr-viewer': typeof PortalHospitalEpcrViewerRoute
  '/portal/hospital/handover': typeof PortalHospitalHandoverRoute
  '/portal/hospital/ift': typeof PortalHospitalIftRoute
  '/portal/hospital/incoming': typeof PortalHospitalIncomingRoute
  '/portal/hospital/queue': typeof PortalHospitalQueueRoute
  '/portal/hospital/reports': typeof PortalHospitalReportsRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/billing/': typeof PortalBillingIndexRoute
  '/portal/cad/': typeof PortalCadIndexRoute
  '/portal/crew/': typeof PortalCrewIndexRoute
  '/portal/dispatchers/': typeof PortalDispatchersIndexRoute
  '/portal/hospital/': typeof PortalHospitalIndexRoute
  '/portal/cad/calls/active': typeof PortalCadCallsActiveRoute
  '/portal/cad/calls/': typeof PortalCadCallsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew-app': typeof CrewAppRoute
  '/login': typeof LoginRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/calls': typeof PortalCallsRoute
  '/portal/epcr': typeof PortalEpcrRoute
  '/portal/fleet': typeof PortalFleetRoute
  '/portal/mobile': typeof PortalMobileRoute
  '/portal/users': typeof PortalUsersRoute
  '/portal': typeof PortalIndexRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/compliance': typeof PortalAdminComplianceRoute
  '/portal/admin/integrations': typeof PortalAdminIntegrationsRoute
  '/portal/admin/master': typeof PortalAdminMasterRoute
  '/portal/admin/modules': typeof PortalAdminModulesRoute
  '/portal/admin/notifications': typeof PortalAdminNotificationsRoute
  '/portal/admin/organizations': typeof PortalAdminOrganizationsRoute
  '/portal/admin/profile': typeof PortalAdminProfileRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/roadmap': typeof PortalAdminRoadmapRoute
  '/portal/admin/roles': typeof PortalAdminRolesRoute
  '/portal/admin/settings': typeof PortalAdminSettingsRoute
  '/portal/admin/users': typeof PortalAdminUsersRoute
  '/portal/admin/workflow': typeof PortalAdminWorkflowRoute
  '/portal/billing/billing': typeof PortalBillingBillingRoute
  '/portal/billing/customers': typeof PortalBillingCustomersRoute
  '/portal/billing/invoices': typeof PortalBillingInvoicesRoute
  '/portal/billing/payments': typeof PortalBillingPaymentsRoute
  '/portal/billing/reports': typeof PortalBillingReportsRoute
  '/portal/billing/settings': typeof PortalBillingSettingsRoute
  '/portal/cad/dispatchers': typeof PortalCadDispatchersRoute
  '/portal/cad/fleet': typeof PortalCadFleetRoute
  '/portal/cad/hospital': typeof PortalCadHospitalRoute
  '/portal/cad/messages': typeof PortalCadMessagesRoute
  '/portal/crew/$id': typeof PortalCrewIdRoute
  '/portal/crew/assignments': typeof PortalCrewAssignmentsRoute
  '/portal/crew/attendance': typeof PortalCrewAttendanceRoute
  '/portal/crew/certifications': typeof PortalCrewCertificationsRoute
  '/portal/crew/communications': typeof PortalCrewCommunicationsRoute
  '/portal/crew/directory': typeof PortalCrewDirectoryRoute
  '/portal/crew/leave': typeof PortalCrewLeaveRoute
  '/portal/crew/performance': typeof PortalCrewPerformanceRoute
  '/portal/crew/roster': typeof PortalCrewRosterRoute
  '/portal/dispatchers/$id': typeof PortalDispatchersIdRoute
  '/portal/hospital/communication': typeof PortalHospitalCommunicationRoute
  '/portal/hospital/epcr-viewer': typeof PortalHospitalEpcrViewerRoute
  '/portal/hospital/handover': typeof PortalHospitalHandoverRoute
  '/portal/hospital/ift': typeof PortalHospitalIftRoute
  '/portal/hospital/incoming': typeof PortalHospitalIncomingRoute
  '/portal/hospital/queue': typeof PortalHospitalQueueRoute
  '/portal/hospital/reports': typeof PortalHospitalReportsRoute
  '/portal/admin': typeof PortalAdminIndexRoute
  '/portal/billing': typeof PortalBillingIndexRoute
  '/portal/cad': typeof PortalCadIndexRoute
  '/portal/crew': typeof PortalCrewIndexRoute
  '/portal/dispatchers': typeof PortalDispatchersIndexRoute
  '/portal/hospital': typeof PortalHospitalIndexRoute
  '/portal/cad/calls/active': typeof PortalCadCallsActiveRoute
  '/portal/cad/calls': typeof PortalCadCallsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew-app': typeof CrewAppRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/billing': typeof PortalBillingRouteWithChildren
  '/portal/cad': typeof PortalCadRouteWithChildren
  '/portal/calls': typeof PortalCallsRoute
  '/portal/crew': typeof PortalCrewRouteWithChildren
  '/portal/dispatchers': typeof PortalDispatchersRouteWithChildren
  '/portal/epcr': typeof PortalEpcrRoute
  '/portal/fleet': typeof PortalFleetRoute
  '/portal/hospital': typeof PortalHospitalRouteWithChildren
  '/portal/mobile': typeof PortalMobileRoute
  '/portal/users': typeof PortalUsersRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/compliance': typeof PortalAdminComplianceRoute
  '/portal/admin/integrations': typeof PortalAdminIntegrationsRoute
  '/portal/admin/master': typeof PortalAdminMasterRoute
  '/portal/admin/modules': typeof PortalAdminModulesRoute
  '/portal/admin/notifications': typeof PortalAdminNotificationsRoute
  '/portal/admin/organizations': typeof PortalAdminOrganizationsRoute
  '/portal/admin/profile': typeof PortalAdminProfileRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/roadmap': typeof PortalAdminRoadmapRoute
  '/portal/admin/roles': typeof PortalAdminRolesRoute
  '/portal/admin/settings': typeof PortalAdminSettingsRoute
  '/portal/admin/users': typeof PortalAdminUsersRoute
  '/portal/admin/workflow': typeof PortalAdminWorkflowRoute
  '/portal/billing/billing': typeof PortalBillingBillingRoute
  '/portal/billing/customers': typeof PortalBillingCustomersRoute
  '/portal/billing/invoices': typeof PortalBillingInvoicesRoute
  '/portal/billing/payments': typeof PortalBillingPaymentsRoute
  '/portal/billing/reports': typeof PortalBillingReportsRoute
  '/portal/billing/settings': typeof PortalBillingSettingsRoute
  '/portal/cad/calls': typeof PortalCadCallsRouteWithChildren
  '/portal/cad/dispatchers': typeof PortalCadDispatchersRoute
  '/portal/cad/fleet': typeof PortalCadFleetRoute
  '/portal/cad/hospital': typeof PortalCadHospitalRoute
  '/portal/cad/messages': typeof PortalCadMessagesRoute
  '/portal/crew/$id': typeof PortalCrewIdRoute
  '/portal/crew/assignments': typeof PortalCrewAssignmentsRoute
  '/portal/crew/attendance': typeof PortalCrewAttendanceRoute
  '/portal/crew/certifications': typeof PortalCrewCertificationsRoute
  '/portal/crew/communications': typeof PortalCrewCommunicationsRoute
  '/portal/crew/directory': typeof PortalCrewDirectoryRoute
  '/portal/crew/leave': typeof PortalCrewLeaveRoute
  '/portal/crew/performance': typeof PortalCrewPerformanceRoute
  '/portal/crew/roster': typeof PortalCrewRosterRoute
  '/portal/dispatchers/$id': typeof PortalDispatchersIdRoute
  '/portal/hospital/communication': typeof PortalHospitalCommunicationRoute
  '/portal/hospital/epcr-viewer': typeof PortalHospitalEpcrViewerRoute
  '/portal/hospital/handover': typeof PortalHospitalHandoverRoute
  '/portal/hospital/ift': typeof PortalHospitalIftRoute
  '/portal/hospital/incoming': typeof PortalHospitalIncomingRoute
  '/portal/hospital/queue': typeof PortalHospitalQueueRoute
  '/portal/hospital/reports': typeof PortalHospitalReportsRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/billing/': typeof PortalBillingIndexRoute
  '/portal/cad/': typeof PortalCadIndexRoute
  '/portal/crew/': typeof PortalCrewIndexRoute
  '/portal/dispatchers/': typeof PortalDispatchersIndexRoute
  '/portal/hospital/': typeof PortalHospitalIndexRoute
  '/portal/cad/calls/active': typeof PortalCadCallsActiveRoute
  '/portal/cad/calls/': typeof PortalCadCallsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crew-app'
    | '/login'
    | '/portal'
    | '/portal/admin'
    | '/portal/analytics'
    | '/portal/billing'
    | '/portal/cad'
    | '/portal/calls'
    | '/portal/crew'
    | '/portal/dispatchers'
    | '/portal/epcr'
    | '/portal/fleet'
    | '/portal/hospital'
    | '/portal/mobile'
    | '/portal/users'
    | '/portal/'
    | '/portal/admin/audit'
    | '/portal/admin/compliance'
    | '/portal/admin/integrations'
    | '/portal/admin/master'
    | '/portal/admin/modules'
    | '/portal/admin/notifications'
    | '/portal/admin/organizations'
    | '/portal/admin/profile'
    | '/portal/admin/reports'
    | '/portal/admin/roadmap'
    | '/portal/admin/roles'
    | '/portal/admin/settings'
    | '/portal/admin/users'
    | '/portal/admin/workflow'
    | '/portal/billing/billing'
    | '/portal/billing/customers'
    | '/portal/billing/invoices'
    | '/portal/billing/payments'
    | '/portal/billing/reports'
    | '/portal/billing/settings'
    | '/portal/cad/calls'
    | '/portal/cad/dispatchers'
    | '/portal/cad/fleet'
    | '/portal/cad/hospital'
    | '/portal/cad/messages'
    | '/portal/crew/$id'
    | '/portal/crew/assignments'
    | '/portal/crew/attendance'
    | '/portal/crew/certifications'
    | '/portal/crew/communications'
    | '/portal/crew/directory'
    | '/portal/crew/leave'
    | '/portal/crew/performance'
    | '/portal/crew/roster'
    | '/portal/dispatchers/$id'
    | '/portal/hospital/communication'
    | '/portal/hospital/epcr-viewer'
    | '/portal/hospital/handover'
    | '/portal/hospital/ift'
    | '/portal/hospital/incoming'
    | '/portal/hospital/queue'
    | '/portal/hospital/reports'
    | '/portal/admin/'
    | '/portal/billing/'
    | '/portal/cad/'
    | '/portal/crew/'
    | '/portal/dispatchers/'
    | '/portal/hospital/'
    | '/portal/cad/calls/active'
    | '/portal/cad/calls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crew-app'
    | '/login'
    | '/portal/analytics'
    | '/portal/calls'
    | '/portal/epcr'
    | '/portal/fleet'
    | '/portal/mobile'
    | '/portal/users'
    | '/portal'
    | '/portal/admin/audit'
    | '/portal/admin/compliance'
    | '/portal/admin/integrations'
    | '/portal/admin/master'
    | '/portal/admin/modules'
    | '/portal/admin/notifications'
    | '/portal/admin/organizations'
    | '/portal/admin/profile'
    | '/portal/admin/reports'
    | '/portal/admin/roadmap'
    | '/portal/admin/roles'
    | '/portal/admin/settings'
    | '/portal/admin/users'
    | '/portal/admin/workflow'
    | '/portal/billing/billing'
    | '/portal/billing/customers'
    | '/portal/billing/invoices'
    | '/portal/billing/payments'
    | '/portal/billing/reports'
    | '/portal/billing/settings'
    | '/portal/cad/dispatchers'
    | '/portal/cad/fleet'
    | '/portal/cad/hospital'
    | '/portal/cad/messages'
    | '/portal/crew/$id'
    | '/portal/crew/assignments'
    | '/portal/crew/attendance'
    | '/portal/crew/certifications'
    | '/portal/crew/communications'
    | '/portal/crew/directory'
    | '/portal/crew/leave'
    | '/portal/crew/performance'
    | '/portal/crew/roster'
    | '/portal/dispatchers/$id'
    | '/portal/hospital/communication'
    | '/portal/hospital/epcr-viewer'
    | '/portal/hospital/handover'
    | '/portal/hospital/ift'
    | '/portal/hospital/incoming'
    | '/portal/hospital/queue'
    | '/portal/hospital/reports'
    | '/portal/admin'
    | '/portal/billing'
    | '/portal/cad'
    | '/portal/crew'
    | '/portal/dispatchers'
    | '/portal/hospital'
    | '/portal/cad/calls/active'
    | '/portal/cad/calls'
  id:
    | '__root__'
    | '/'
    | '/crew-app'
    | '/login'
    | '/portal'
    | '/portal/admin'
    | '/portal/analytics'
    | '/portal/billing'
    | '/portal/cad'
    | '/portal/calls'
    | '/portal/crew'
    | '/portal/dispatchers'
    | '/portal/epcr'
    | '/portal/fleet'
    | '/portal/hospital'
    | '/portal/mobile'
    | '/portal/users'
    | '/portal/'
    | '/portal/admin/audit'
    | '/portal/admin/compliance'
    | '/portal/admin/integrations'
    | '/portal/admin/master'
    | '/portal/admin/modules'
    | '/portal/admin/notifications'
    | '/portal/admin/organizations'
    | '/portal/admin/profile'
    | '/portal/admin/reports'
    | '/portal/admin/roadmap'
    | '/portal/admin/roles'
    | '/portal/admin/settings'
    | '/portal/admin/users'
    | '/portal/admin/workflow'
    | '/portal/billing/billing'
    | '/portal/billing/customers'
    | '/portal/billing/invoices'
    | '/portal/billing/payments'
    | '/portal/billing/reports'
    | '/portal/billing/settings'
    | '/portal/cad/calls'
    | '/portal/cad/dispatchers'
    | '/portal/cad/fleet'
    | '/portal/cad/hospital'
    | '/portal/cad/messages'
    | '/portal/crew/$id'
    | '/portal/crew/assignments'
    | '/portal/crew/attendance'
    | '/portal/crew/certifications'
    | '/portal/crew/communications'
    | '/portal/crew/directory'
    | '/portal/crew/leave'
    | '/portal/crew/performance'
    | '/portal/crew/roster'
    | '/portal/dispatchers/$id'
    | '/portal/hospital/communication'
    | '/portal/hospital/epcr-viewer'
    | '/portal/hospital/handover'
    | '/portal/hospital/ift'
    | '/portal/hospital/incoming'
    | '/portal/hospital/queue'
    | '/portal/hospital/reports'
    | '/portal/admin/'
    | '/portal/billing/'
    | '/portal/cad/'
    | '/portal/crew/'
    | '/portal/dispatchers/'
    | '/portal/hospital/'
    | '/portal/cad/calls/active'
    | '/portal/cad/calls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewAppRoute: typeof CrewAppRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew-app': {
      id: '/crew-app'
      path: '/crew-app'
      fullPath: '/crew-app'
      preLoaderRoute: typeof CrewAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/users': {
      id: '/portal/users'
      path: '/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof PortalUsersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/mobile': {
      id: '/portal/mobile'
      path: '/mobile'
      fullPath: '/portal/mobile'
      preLoaderRoute: typeof PortalMobileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/hospital': {
      id: '/portal/hospital'
      path: '/hospital'
      fullPath: '/portal/hospital'
      preLoaderRoute: typeof PortalHospitalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/fleet': {
      id: '/portal/fleet'
      path: '/fleet'
      fullPath: '/portal/fleet'
      preLoaderRoute: typeof PortalFleetRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/epcr': {
      id: '/portal/epcr'
      path: '/epcr'
      fullPath: '/portal/epcr'
      preLoaderRoute: typeof PortalEpcrRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dispatchers': {
      id: '/portal/dispatchers'
      path: '/dispatchers'
      fullPath: '/portal/dispatchers'
      preLoaderRoute: typeof PortalDispatchersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/crew': {
      id: '/portal/crew'
      path: '/crew'
      fullPath: '/portal/crew'
      preLoaderRoute: typeof PortalCrewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/calls': {
      id: '/portal/calls'
      path: '/calls'
      fullPath: '/portal/calls'
      preLoaderRoute: typeof PortalCallsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cad': {
      id: '/portal/cad'
      path: '/cad'
      fullPath: '/portal/cad'
      preLoaderRoute: typeof PortalCadRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/analytics': {
      id: '/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/hospital/': {
      id: '/portal/hospital/'
      path: '/'
      fullPath: '/portal/hospital/'
      preLoaderRoute: typeof PortalHospitalIndexRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/dispatchers/': {
      id: '/portal/dispatchers/'
      path: '/'
      fullPath: '/portal/dispatchers/'
      preLoaderRoute: typeof PortalDispatchersIndexRouteImport
      parentRoute: typeof PortalDispatchersRoute
    }
    '/portal/crew/': {
      id: '/portal/crew/'
      path: '/'
      fullPath: '/portal/crew/'
      preLoaderRoute: typeof PortalCrewIndexRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/cad/': {
      id: '/portal/cad/'
      path: '/'
      fullPath: '/portal/cad/'
      preLoaderRoute: typeof PortalCadIndexRouteImport
      parentRoute: typeof PortalCadRoute
    }
    '/portal/billing/': {
      id: '/portal/billing/'
      path: '/'
      fullPath: '/portal/billing/'
      preLoaderRoute: typeof PortalBillingIndexRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/admin/': {
      id: '/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof PortalAdminIndexRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/hospital/reports': {
      id: '/portal/hospital/reports'
      path: '/reports'
      fullPath: '/portal/hospital/reports'
      preLoaderRoute: typeof PortalHospitalReportsRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/hospital/queue': {
      id: '/portal/hospital/queue'
      path: '/queue'
      fullPath: '/portal/hospital/queue'
      preLoaderRoute: typeof PortalHospitalQueueRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/hospital/incoming': {
      id: '/portal/hospital/incoming'
      path: '/incoming'
      fullPath: '/portal/hospital/incoming'
      preLoaderRoute: typeof PortalHospitalIncomingRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/hospital/ift': {
      id: '/portal/hospital/ift'
      path: '/ift'
      fullPath: '/portal/hospital/ift'
      preLoaderRoute: typeof PortalHospitalIftRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/hospital/handover': {
      id: '/portal/hospital/handover'
      path: '/handover'
      fullPath: '/portal/hospital/handover'
      preLoaderRoute: typeof PortalHospitalHandoverRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/hospital/epcr-viewer': {
      id: '/portal/hospital/epcr-viewer'
      path: '/epcr-viewer'
      fullPath: '/portal/hospital/epcr-viewer'
      preLoaderRoute: typeof PortalHospitalEpcrViewerRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/hospital/communication': {
      id: '/portal/hospital/communication'
      path: '/communication'
      fullPath: '/portal/hospital/communication'
      preLoaderRoute: typeof PortalHospitalCommunicationRouteImport
      parentRoute: typeof PortalHospitalRoute
    }
    '/portal/dispatchers/$id': {
      id: '/portal/dispatchers/$id'
      path: '/$id'
      fullPath: '/portal/dispatchers/$id'
      preLoaderRoute: typeof PortalDispatchersIdRouteImport
      parentRoute: typeof PortalDispatchersRoute
    }
    '/portal/crew/roster': {
      id: '/portal/crew/roster'
      path: '/roster'
      fullPath: '/portal/crew/roster'
      preLoaderRoute: typeof PortalCrewRosterRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/performance': {
      id: '/portal/crew/performance'
      path: '/performance'
      fullPath: '/portal/crew/performance'
      preLoaderRoute: typeof PortalCrewPerformanceRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/leave': {
      id: '/portal/crew/leave'
      path: '/leave'
      fullPath: '/portal/crew/leave'
      preLoaderRoute: typeof PortalCrewLeaveRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/directory': {
      id: '/portal/crew/directory'
      path: '/directory'
      fullPath: '/portal/crew/directory'
      preLoaderRoute: typeof PortalCrewDirectoryRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/communications': {
      id: '/portal/crew/communications'
      path: '/communications'
      fullPath: '/portal/crew/communications'
      preLoaderRoute: typeof PortalCrewCommunicationsRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/certifications': {
      id: '/portal/crew/certifications'
      path: '/certifications'
      fullPath: '/portal/crew/certifications'
      preLoaderRoute: typeof PortalCrewCertificationsRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/attendance': {
      id: '/portal/crew/attendance'
      path: '/attendance'
      fullPath: '/portal/crew/attendance'
      preLoaderRoute: typeof PortalCrewAttendanceRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/assignments': {
      id: '/portal/crew/assignments'
      path: '/assignments'
      fullPath: '/portal/crew/assignments'
      preLoaderRoute: typeof PortalCrewAssignmentsRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/crew/$id': {
      id: '/portal/crew/$id'
      path: '/$id'
      fullPath: '/portal/crew/$id'
      preLoaderRoute: typeof PortalCrewIdRouteImport
      parentRoute: typeof PortalCrewRoute
    }
    '/portal/cad/messages': {
      id: '/portal/cad/messages'
      path: '/messages'
      fullPath: '/portal/cad/messages'
      preLoaderRoute: typeof PortalCadMessagesRouteImport
      parentRoute: typeof PortalCadRoute
    }
    '/portal/cad/hospital': {
      id: '/portal/cad/hospital'
      path: '/hospital'
      fullPath: '/portal/cad/hospital'
      preLoaderRoute: typeof PortalCadHospitalRouteImport
      parentRoute: typeof PortalCadRoute
    }
    '/portal/cad/fleet': {
      id: '/portal/cad/fleet'
      path: '/fleet'
      fullPath: '/portal/cad/fleet'
      preLoaderRoute: typeof PortalCadFleetRouteImport
      parentRoute: typeof PortalCadRoute
    }
    '/portal/cad/dispatchers': {
      id: '/portal/cad/dispatchers'
      path: '/dispatchers'
      fullPath: '/portal/cad/dispatchers'
      preLoaderRoute: typeof PortalCadDispatchersRouteImport
      parentRoute: typeof PortalCadRoute
    }
    '/portal/cad/calls': {
      id: '/portal/cad/calls'
      path: '/calls'
      fullPath: '/portal/cad/calls'
      preLoaderRoute: typeof PortalCadCallsRouteImport
      parentRoute: typeof PortalCadRoute
    }
    '/portal/billing/settings': {
      id: '/portal/billing/settings'
      path: '/settings'
      fullPath: '/portal/billing/settings'
      preLoaderRoute: typeof PortalBillingSettingsRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/billing/reports': {
      id: '/portal/billing/reports'
      path: '/reports'
      fullPath: '/portal/billing/reports'
      preLoaderRoute: typeof PortalBillingReportsRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/billing/payments': {
      id: '/portal/billing/payments'
      path: '/payments'
      fullPath: '/portal/billing/payments'
      preLoaderRoute: typeof PortalBillingPaymentsRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/billing/invoices': {
      id: '/portal/billing/invoices'
      path: '/invoices'
      fullPath: '/portal/billing/invoices'
      preLoaderRoute: typeof PortalBillingInvoicesRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/billing/customers': {
      id: '/portal/billing/customers'
      path: '/customers'
      fullPath: '/portal/billing/customers'
      preLoaderRoute: typeof PortalBillingCustomersRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/billing/billing': {
      id: '/portal/billing/billing'
      path: '/billing'
      fullPath: '/portal/billing/billing'
      preLoaderRoute: typeof PortalBillingBillingRouteImport
      parentRoute: typeof PortalBillingRoute
    }
    '/portal/admin/workflow': {
      id: '/portal/admin/workflow'
      path: '/workflow'
      fullPath: '/portal/admin/workflow'
      preLoaderRoute: typeof PortalAdminWorkflowRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/users': {
      id: '/portal/admin/users'
      path: '/users'
      fullPath: '/portal/admin/users'
      preLoaderRoute: typeof PortalAdminUsersRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/settings': {
      id: '/portal/admin/settings'
      path: '/settings'
      fullPath: '/portal/admin/settings'
      preLoaderRoute: typeof PortalAdminSettingsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/roles': {
      id: '/portal/admin/roles'
      path: '/roles'
      fullPath: '/portal/admin/roles'
      preLoaderRoute: typeof PortalAdminRolesRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/roadmap': {
      id: '/portal/admin/roadmap'
      path: '/roadmap'
      fullPath: '/portal/admin/roadmap'
      preLoaderRoute: typeof PortalAdminRoadmapRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/reports': {
      id: '/portal/admin/reports'
      path: '/reports'
      fullPath: '/portal/admin/reports'
      preLoaderRoute: typeof PortalAdminReportsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/profile': {
      id: '/portal/admin/profile'
      path: '/profile'
      fullPath: '/portal/admin/profile'
      preLoaderRoute: typeof PortalAdminProfileRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/organizations': {
      id: '/portal/admin/organizations'
      path: '/organizations'
      fullPath: '/portal/admin/organizations'
      preLoaderRoute: typeof PortalAdminOrganizationsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/notifications': {
      id: '/portal/admin/notifications'
      path: '/notifications'
      fullPath: '/portal/admin/notifications'
      preLoaderRoute: typeof PortalAdminNotificationsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/modules': {
      id: '/portal/admin/modules'
      path: '/modules'
      fullPath: '/portal/admin/modules'
      preLoaderRoute: typeof PortalAdminModulesRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/master': {
      id: '/portal/admin/master'
      path: '/master'
      fullPath: '/portal/admin/master'
      preLoaderRoute: typeof PortalAdminMasterRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/integrations': {
      id: '/portal/admin/integrations'
      path: '/integrations'
      fullPath: '/portal/admin/integrations'
      preLoaderRoute: typeof PortalAdminIntegrationsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/compliance': {
      id: '/portal/admin/compliance'
      path: '/compliance'
      fullPath: '/portal/admin/compliance'
      preLoaderRoute: typeof PortalAdminComplianceRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/audit': {
      id: '/portal/admin/audit'
      path: '/audit'
      fullPath: '/portal/admin/audit'
      preLoaderRoute: typeof PortalAdminAuditRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/cad/calls/': {
      id: '/portal/cad/calls/'
      path: '/'
      fullPath: '/portal/cad/calls/'
      preLoaderRoute: typeof PortalCadCallsIndexRouteImport
      parentRoute: typeof PortalCadCallsRoute
    }
    '/portal/cad/calls/active': {
      id: '/portal/cad/calls/active'
      path: '/active'
      fullPath: '/portal/cad/calls/active'
      preLoaderRoute: typeof PortalCadCallsActiveRouteImport
      parentRoute: typeof PortalCadCallsRoute
    }
  }
}

interface PortalAdminRouteChildren {
  PortalAdminAuditRoute: typeof PortalAdminAuditRoute
  PortalAdminComplianceRoute: typeof PortalAdminComplianceRoute
  PortalAdminIntegrationsRoute: typeof PortalAdminIntegrationsRoute
  PortalAdminMasterRoute: typeof PortalAdminMasterRoute
  PortalAdminModulesRoute: typeof PortalAdminModulesRoute
  PortalAdminNotificationsRoute: typeof PortalAdminNotificationsRoute
  PortalAdminOrganizationsRoute: typeof PortalAdminOrganizationsRoute
  PortalAdminProfileRoute: typeof PortalAdminProfileRoute
  PortalAdminReportsRoute: typeof PortalAdminReportsRoute
  PortalAdminRoadmapRoute: typeof PortalAdminRoadmapRoute
  PortalAdminRolesRoute: typeof PortalAdminRolesRoute
  PortalAdminSettingsRoute: typeof PortalAdminSettingsRoute
  PortalAdminUsersRoute: typeof PortalAdminUsersRoute
  PortalAdminWorkflowRoute: typeof PortalAdminWorkflowRoute
  PortalAdminIndexRoute: typeof PortalAdminIndexRoute
}

const PortalAdminRouteChildren: PortalAdminRouteChildren = {
  PortalAdminAuditRoute: PortalAdminAuditRoute,
  PortalAdminComplianceRoute: PortalAdminComplianceRoute,
  PortalAdminIntegrationsRoute: PortalAdminIntegrationsRoute,
  PortalAdminMasterRoute: PortalAdminMasterRoute,
  PortalAdminModulesRoute: PortalAdminModulesRoute,
  PortalAdminNotificationsRoute: PortalAdminNotificationsRoute,
  PortalAdminOrganizationsRoute: PortalAdminOrganizationsRoute,
  PortalAdminProfileRoute: PortalAdminProfileRoute,
  PortalAdminReportsRoute: PortalAdminReportsRoute,
  PortalAdminRoadmapRoute: PortalAdminRoadmapRoute,
  PortalAdminRolesRoute: PortalAdminRolesRoute,
  PortalAdminSettingsRoute: PortalAdminSettingsRoute,
  PortalAdminUsersRoute: PortalAdminUsersRoute,
  PortalAdminWorkflowRoute: PortalAdminWorkflowRoute,
  PortalAdminIndexRoute: PortalAdminIndexRoute,
}

const PortalAdminRouteWithChildren = PortalAdminRoute._addFileChildren(
  PortalAdminRouteChildren,
)

interface PortalBillingRouteChildren {
  PortalBillingBillingRoute: typeof PortalBillingBillingRoute
  PortalBillingCustomersRoute: typeof PortalBillingCustomersRoute
  PortalBillingInvoicesRoute: typeof PortalBillingInvoicesRoute
  PortalBillingPaymentsRoute: typeof PortalBillingPaymentsRoute
  PortalBillingReportsRoute: typeof PortalBillingReportsRoute
  PortalBillingSettingsRoute: typeof PortalBillingSettingsRoute
  PortalBillingIndexRoute: typeof PortalBillingIndexRoute
}

const PortalBillingRouteChildren: PortalBillingRouteChildren = {
  PortalBillingBillingRoute: PortalBillingBillingRoute,
  PortalBillingCustomersRoute: PortalBillingCustomersRoute,
  PortalBillingInvoicesRoute: PortalBillingInvoicesRoute,
  PortalBillingPaymentsRoute: PortalBillingPaymentsRoute,
  PortalBillingReportsRoute: PortalBillingReportsRoute,
  PortalBillingSettingsRoute: PortalBillingSettingsRoute,
  PortalBillingIndexRoute: PortalBillingIndexRoute,
}

const PortalBillingRouteWithChildren = PortalBillingRoute._addFileChildren(
  PortalBillingRouteChildren,
)

interface PortalCadCallsRouteChildren {
  PortalCadCallsActiveRoute: typeof PortalCadCallsActiveRoute
  PortalCadCallsIndexRoute: typeof PortalCadCallsIndexRoute
}

const PortalCadCallsRouteChildren: PortalCadCallsRouteChildren = {
  PortalCadCallsActiveRoute: PortalCadCallsActiveRoute,
  PortalCadCallsIndexRoute: PortalCadCallsIndexRoute,
}

const PortalCadCallsRouteWithChildren = PortalCadCallsRoute._addFileChildren(
  PortalCadCallsRouteChildren,
)

interface PortalCadRouteChildren {
  PortalCadCallsRoute: typeof PortalCadCallsRouteWithChildren
  PortalCadDispatchersRoute: typeof PortalCadDispatchersRoute
  PortalCadFleetRoute: typeof PortalCadFleetRoute
  PortalCadHospitalRoute: typeof PortalCadHospitalRoute
  PortalCadMessagesRoute: typeof PortalCadMessagesRoute
  PortalCadIndexRoute: typeof PortalCadIndexRoute
}

const PortalCadRouteChildren: PortalCadRouteChildren = {
  PortalCadCallsRoute: PortalCadCallsRouteWithChildren,
  PortalCadDispatchersRoute: PortalCadDispatchersRoute,
  PortalCadFleetRoute: PortalCadFleetRoute,
  PortalCadHospitalRoute: PortalCadHospitalRoute,
  PortalCadMessagesRoute: PortalCadMessagesRoute,
  PortalCadIndexRoute: PortalCadIndexRoute,
}

const PortalCadRouteWithChildren = PortalCadRoute._addFileChildren(
  PortalCadRouteChildren,
)

interface PortalCrewRouteChildren {
  PortalCrewIdRoute: typeof PortalCrewIdRoute
  PortalCrewAssignmentsRoute: typeof PortalCrewAssignmentsRoute
  PortalCrewAttendanceRoute: typeof PortalCrewAttendanceRoute
  PortalCrewCertificationsRoute: typeof PortalCrewCertificationsRoute
  PortalCrewCommunicationsRoute: typeof PortalCrewCommunicationsRoute
  PortalCrewDirectoryRoute: typeof PortalCrewDirectoryRoute
  PortalCrewLeaveRoute: typeof PortalCrewLeaveRoute
  PortalCrewPerformanceRoute: typeof PortalCrewPerformanceRoute
  PortalCrewRosterRoute: typeof PortalCrewRosterRoute
  PortalCrewIndexRoute: typeof PortalCrewIndexRoute
}

const PortalCrewRouteChildren: PortalCrewRouteChildren = {
  PortalCrewIdRoute: PortalCrewIdRoute,
  PortalCrewAssignmentsRoute: PortalCrewAssignmentsRoute,
  PortalCrewAttendanceRoute: PortalCrewAttendanceRoute,
  PortalCrewCertificationsRoute: PortalCrewCertificationsRoute,
  PortalCrewCommunicationsRoute: PortalCrewCommunicationsRoute,
  PortalCrewDirectoryRoute: PortalCrewDirectoryRoute,
  PortalCrewLeaveRoute: PortalCrewLeaveRoute,
  PortalCrewPerformanceRoute: PortalCrewPerformanceRoute,
  PortalCrewRosterRoute: PortalCrewRosterRoute,
  PortalCrewIndexRoute: PortalCrewIndexRoute,
}

const PortalCrewRouteWithChildren = PortalCrewRoute._addFileChildren(
  PortalCrewRouteChildren,
)

interface PortalDispatchersRouteChildren {
  PortalDispatchersIdRoute: typeof PortalDispatchersIdRoute
  PortalDispatchersIndexRoute: typeof PortalDispatchersIndexRoute
}

const PortalDispatchersRouteChildren: PortalDispatchersRouteChildren = {
  PortalDispatchersIdRoute: PortalDispatchersIdRoute,
  PortalDispatchersIndexRoute: PortalDispatchersIndexRoute,
}

const PortalDispatchersRouteWithChildren =
  PortalDispatchersRoute._addFileChildren(PortalDispatchersRouteChildren)

interface PortalHospitalRouteChildren {
  PortalHospitalCommunicationRoute: typeof PortalHospitalCommunicationRoute
  PortalHospitalEpcrViewerRoute: typeof PortalHospitalEpcrViewerRoute
  PortalHospitalHandoverRoute: typeof PortalHospitalHandoverRoute
  PortalHospitalIftRoute: typeof PortalHospitalIftRoute
  PortalHospitalIncomingRoute: typeof PortalHospitalIncomingRoute
  PortalHospitalQueueRoute: typeof PortalHospitalQueueRoute
  PortalHospitalReportsRoute: typeof PortalHospitalReportsRoute
  PortalHospitalIndexRoute: typeof PortalHospitalIndexRoute
}

const PortalHospitalRouteChildren: PortalHospitalRouteChildren = {
  PortalHospitalCommunicationRoute: PortalHospitalCommunicationRoute,
  PortalHospitalEpcrViewerRoute: PortalHospitalEpcrViewerRoute,
  PortalHospitalHandoverRoute: PortalHospitalHandoverRoute,
  PortalHospitalIftRoute: PortalHospitalIftRoute,
  PortalHospitalIncomingRoute: PortalHospitalIncomingRoute,
  PortalHospitalQueueRoute: PortalHospitalQueueRoute,
  PortalHospitalReportsRoute: PortalHospitalReportsRoute,
  PortalHospitalIndexRoute: PortalHospitalIndexRoute,
}

const PortalHospitalRouteWithChildren = PortalHospitalRoute._addFileChildren(
  PortalHospitalRouteChildren,
)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRouteWithChildren
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalBillingRoute: typeof PortalBillingRouteWithChildren
  PortalCadRoute: typeof PortalCadRouteWithChildren
  PortalCallsRoute: typeof PortalCallsRoute
  PortalCrewRoute: typeof PortalCrewRouteWithChildren
  PortalDispatchersRoute: typeof PortalDispatchersRouteWithChildren
  PortalEpcrRoute: typeof PortalEpcrRoute
  PortalFleetRoute: typeof PortalFleetRoute
  PortalHospitalRoute: typeof PortalHospitalRouteWithChildren
  PortalMobileRoute: typeof PortalMobileRoute
  PortalUsersRoute: typeof PortalUsersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRouteWithChildren,
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalBillingRoute: PortalBillingRouteWithChildren,
  PortalCadRoute: PortalCadRouteWithChildren,
  PortalCallsRoute: PortalCallsRoute,
  PortalCrewRoute: PortalCrewRouteWithChildren,
  PortalDispatchersRoute: PortalDispatchersRouteWithChildren,
  PortalEpcrRoute: PortalEpcrRoute,
  PortalFleetRoute: PortalFleetRoute,
  PortalHospitalRoute: PortalHospitalRouteWithChildren,
  PortalMobileRoute: PortalMobileRoute,
  PortalUsersRoute: PortalUsersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewAppRoute: CrewAppRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
